### ISSUE TITLE
Decide which starter/template

### ISSUE THREAD

**Issue by jhsuP** [crypto-cats/bowfolios-mobile#3]
https://demos.creative-tim.com/material-kit-react-native/?_ga=2.255637576.1114859809.1598669178-1489912262.1598669178
https://nativebase.io/
https://akveo.github.io/react-native-ui-kitten/#kitten-tricks
https://medium.com/javascript-in-plain-english/10-awesome-react-native-ui-component-libraries-you-should-know-cd3296d99c0b

**Comment by Pauline-Peihan-Wu** [comment]
https://github.com/flatlogic/react-native-starter
https://github.com/invertase/react-native-template/tree/master/template
https://github.com/tassdr/react-native-template/tree/master/ReactNativeTemplate
https://github.com/opp100/react-native-template
